### PR TITLE
Fixes #187 : Center image inside container with "invert" option

### LINKED ISSUE #187: Centering to bottom of container when zooming out with contain: 'invert'
As the title states. When zooming out of and image and the image becomes smaller than the container the image "docks" to the bottom or to the right of the container instead of the center.

Does anyone know if this is intended, or have I been incompetent at implementing the library correctly.

Thanks in advance for any responses.

### PR DESCRIPTION
**Pull request by aymerix**
I faced the same problem described in the issue #187 and this little patch seems to solve it.

### CODE REVIEW

**Comment by pagameba** [comment]
+1 this patch fixes the problem for me, would love to see this merged and pushed to bower (hint, hint)

**Comment by markfeimer** [comment]
Any news on this getting merged into the main branch?

**Comment by markfeimer** [comment]
Thanks!  Sorry to be a pain, but would it also be possible for the dist/jquery.panzoom.js to be re-built?  It looks like that is the file that is referenced in bower.json as the main.

**Comment by timmywil** [comment]
@markfeimer Yup, releasing soon.

**Comment by markfeimer** [comment]
@timmywil Awesomeness.  Thank you!

**Comment by markfeimer** [comment]
@timmywil Is there an ETA for the release?

**Pull request merged**
