### PR TITLE
Issue #263: allow panzoom to work on rotated/transformed images

### PR DESCRIPTION
**Pull request by jcnventura**
### PR Checklist
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [X] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not *master*.
- [X] I have run `grunt` against my changes and both linting and tests pass.
- [X] I have added tests to prove my fix is affective or my feature works. This can be done in the form of unit tests in `test/bdd/test.js` or a new demo on `demo/index.html`.
- [ ] I have added or edited necessary documentation in the README.md (if appropriate).

### Description
This PR modifies the zoom function of panzoom to work on images that were rotated via CSS before being zoomed. It also stops the usage of matrix[0] as the 'scale' value.

**Fixes**: #263

### CODE REVIEW

**Comment by timmywil** [comment]
This is definitely the right direction, but it needs tests. I have a lot of things going on right now, so I can't spend too much time on Panzoom, but if you add tests for this, I'll merge it.

**Comment by jcnventura** [comment]
Tests added.

**Comment by timmywil** [comment]
Thanks! Tests need to pass in Travis before landing, tho.

**Comment by jcnventura** [comment]
I think the Travis CI is broken. It's not the tests failing to pass.. It's Travis itself not being able to even start them.

**Comment by jcnventura** [comment]
Thanks for updating the node versions used in the test.. It's strange that the tests pass in the browser, but not in "npm test".

**Comment by jcnventura** [comment]
OK. There was a minor bug in the pan area (squashed by the --amend I did to keep it under a single commit).. And the tests had to be corrected to account for floating point comparison.

Tests are now passing.

**Comment by jcnventura** [comment]
Yay! Thanks :)

**Pull request merged**
